pipeline{
           agent {
        label{
           label "built-in"
				customWorkspace "/mnt/"
        }
    }
    stages{
        stage("building-project"){
            steps{
               sh "sudo git clone https://github.com/rohaanuv/game-of-life.git"
               sh '''cd game-of-life/
               sudo mvn clean install
               '''
               sh "sudo chmod -R 777 game-of-life"
            }
        }
        
         stage("deply-yml"){
             agent {
        label{
           label "built-in"
				customWorkspace "/mnt/game-of-life"
        }
    }
            steps{ 
                sh "pwd"
                sh "ls -ltra"
                
              sh '''sudo su -c "ansible-playbook main.yml" ron'''
                
            }
        }

    }
}